## 1. Basics

### 1.1 General

In [2]:
import pandas as pd
import numpy as np

In [4]:
data = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [5]:
columns = ["i", "j", "k"]
indexes = ["a", "b", "c"]

df = pd.DataFrame(data, columns=columns, index=indexes)

In [6]:
df

   i  j  k
a  1  0  0
b  0  1  0
c  0  0  1

In [7]:
df = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 6]
    ]

columns = ["A", "B", "C"]

pd.DataFrame(df, columns=columns)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  6

### 1.2 DataFrame from a dictionary

In [8]:
states = ["São Paulo", "Paraná", "Maranhão", "Mato Grosso"]
population = [46649132, 11890517, 7018211, 3836399]

In [9]:
dict_states = {"States":states, "Population":population}

In [10]:
df_pop = pd.DataFrame(dict_states)

In [11]:
df_pop

        States  Population
0    São Paulo    46649132
1       Paraná    11890517
2     Maranhão     7018211
3  Mato Grosso     3836399

### 1.3 DataFrame from a csv

In [12]:
df_exams = pd.read_csv("StudentsPerformance.csv")

In [13]:
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [14]:
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [15]:
df_exams.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [16]:
df_exams.shape

(1000, 8)

In [29]:
n = 1000
pd.set_option("display.max_rows", 1000)

## 2. Methods

In [31]:
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [32]:
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [33]:
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [34]:
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [35]:
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

 ## 3. Functions

In [37]:
len(df_exams)

1000

In [40]:
max(df_exams.index)

999

In [41]:
min(df_exams.index)

0