### 1. Configuration

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Car_sales.csv")
df.head()

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639

In [3]:
columns = [
    "Manufacturer", "Sales_in_thousands", "Vehicle_type", 
    "Price_in_thousands", "Engine_size", "Horsepower", 
    "Fuel_capacity"
    ]

df = df[columns]
df.head()

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4

In [4]:
df.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Engine_size            31
Horsepower             66
Fuel_capacity          55
dtype: int64

### 2. agg()

In [ ]:
numerical = []
string = []

for i in columns:
    if df.dtypes[i] == "O":
        string.append(i)
    else:
        numerical.append(i)

In [22]:
df[numerical].agg("sum")

Sales_in_thousands     8320.698
Price_in_thousands     4245.567
Engine_size             477.500
Horsepower            29008.000
Fuel_capacity          2800.500
dtype: float64

In [21]:
df[numerical].agg("mean")

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [24]:
df[numerical].agg(["mean", "count", "sum"])

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
mean,52.998076,27.390755,3.060897,185.948718,17.951923
count,157.000000,155.000000,156.000000,156.000000,156.000000
sum,8320.698000,4245.567000,477.500000,29008.000000,2800.500000

In [ ]:
df[numerical].agg({
    "Sales_in_thousands":["sum", "mean"],
    "Price_in_thousands":["sum", "max"]
    }
)

      Sales_in_thousands  Price_in_thousands
sum          8320.698000            4245.567
mean           52.998076                 NaN
max                  NaN              85.500

In [27]:
df[["Sales_in_thousands", "Price_in_thousands"]].agg("sum", axis=1)

0      38.419
1      67.784
2      14.114
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [28]:
df.agg(sum_of_sales = ("Sales_in_thousands", "sum"),
       sum_of_price = ("Price_in_thousands", "sum"))

              Sales_in_thousands  Price_in_thousands
sum_of_sales            8320.698                 NaN
sum_of_price                 NaN            4245.567

### 3. The split-apply-combine strategy

In [29]:
df["Vehicle_type"].value_counts()

Vehicle_type
Passenger    116
Car           41
Name: count, dtype: int64

In [30]:
passanger_filter = df["Vehicle_type"] == "Passenger"
car_filter       = df["Vehicle_type"] == "Car"

In [34]:
passanger_mean = df[passanger_filter]["Sales_in_thousands"].mean()

In [35]:
car_mean = df[car_filter]["Sales_in_thousands"].mean()

In [36]:
pd.DataFrame({
    "Vehicle_type":["Car", "Passenger"],
    "Sales_in_thousands":[car_mean, passanger_mean]
    })

  Vehicle_type  Sales_in_thousands
0          Car           80.622293
1    Passenger           43.234345