### 1. Configuration

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("gdp.csv", encoding="latin-1")
df.head()

   unid wbid      country  year        SES      gdppc  yrseduc  popshare
0     4  AFG  Afghanistan  1970   3.474212  709.00000      NaN  0.003097
1     4  AFG  Afghanistan  1920  26.968016  731.75677      NaN  0.003245
2     4  AFG  Afghanistan  1990   1.269530  604.00000      NaN  0.002347
3     4  AFG  Afghanistan  1960  15.763076  739.00000      NaN  0.003039
4     4  AFG  Afghanistan  2000   2.061114  565.00000      NaN  0.003309

### 2. pivot()

In [6]:
df.pivot(index="country", columns="year", values="gdppc").round(2)

year,1880,1890,1900,1910,1920,1930,1940,1950,1960,1970,1980,1990,2000,2010
country,,,,,,,,,,,,,,
Afghanistan,585.47,635.93,686.40,736.86,731.76,702.84,673.92,645.0,739.0,709.0,690.0,604.00,565.00,1662.80
Albania,522.00,598.00,685.00,780.00,861.31,929.57,965.29,1001.0,1451.0,2004.0,2347.0,4557.41,5470.02,9927.18
Algeria,819.19,923.37,1027.56,1131.74,1201.22,1255.81,1310.41,1365.0,2088.0,2249.0,3152.0,10238.88,10211.10,12898.30
Angola,533.67,567.33,601.00,628.69,682.63,747.81,813.00,1052.0,1253.0,1768.0,961.0,4806.43,3831.00,6492.18
Argentina,1731.50,2152.00,2756.00,3822.00,3473.00,4080.00,4161.00,4987.0,5559.0,7302.0,8206.0,10833.50,14924.37,18794.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,653.00,737.00,821.00,886.00,1173.00,3444.00,4045.00,7462.0,9646.0,10672.0,10139.0,14450.68,14417.10,16563.40
Vietnam,556.63,608.26,659.88,711.51,713.95,695.30,676.65,658.0,799.0,735.0,757.0,1501.14,2649.72,4486.26
Yemen,811.77,881.53,951.30,1021.07,1017.22,981.81,946.41,911.0,964.0,1230.0,2290.0,3353.79,3911.22,4481.55
Zambia,533.67,567.33,601.00,628.69,682.63,747.81,813.00,661.0,960.0,1073.0,911.0,2308.60,2092.26,3263.39
Zimbabwe,533.67,567.33,601.00,628.69,682.63,747.81,813.00,701.0,938.0,1282.0,1295.0,2526.07,2521.35,1388.97

### 3. pivot_table()

In [8]:
df_sales = pd.read_excel("supermarket_sales.xlsx")
df_sales.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33:00,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00,Ewallet,604.17,4.761905,30.2085,5.3

In [ ]:
columns = ["Quantity", "Rating", "Total", "Unit price", "cogs", "gross income", "gross margin percentage"]

df_sales.pivot_table(index="Gender", aggfunc="sum", values=columns)

,Quantity,Rating,Total,Unit price,cogs,gross income,gross margin percentage
Gender,,,,,,,
Female,2869,3489.2,167882.925,27687.24,159888.50,7994.425,2385.714286
Male,2641,3483.5,155083.824,27984.89,147698.88,7384.944,2376.190476

In [14]:
columns = ["Quantity", "Total"]

df_sales.pivot_table(
    index="Gender", 
    aggfunc="sum", 
    values=columns
    )

        Quantity       Total
Gender
Female      2869  167882.925
Male        2641  155083.824

In [16]:
columns = ["Total"]
categories = ["Product line"]

df_sales.pivot_table(
    index="Gender", 
    aggfunc="sum", 
    values=columns,
    columns=categories
    )

                              Total                                         \
Product line Electronic accessories Fashion accessories Food and beverages
Gender
Female                   27102.0225           30437.400         33170.9175
Male                     27235.5090           23868.495         22973.9265


Product line Health and beauty Home and lifestyle Sports and travel
Gender
Female              18560.9865         30036.8775        28574.7210
Male                30632.7525         23825.0355        26548.1055